name: file
on:
  workflow_dispatch:
  push:
jobs:
  ubuntu:
    runs-on: ubuntu-latest   
    steps:
        - name: install golang
          run: |
            mkdir /root/golang
            cd /root/golang
            wget https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
            tar xf go1.24.2.linux-amd64.tar.gz
        - name: pull git repo
          run: |
            cd /root
            wget https://github.com/0031400/file/archive/refs/heads/master.zip
            unzip main.zip
        - name: build
          run: |
            cd /root/file-master
            export PATH=/root/golang/go/bin:$PATH
            go build -o file-1.0-linux-amd64
        - name: upload
          uses: softprops/action-gh-release@v2
          with:
            token: ${{ secrets.token }}
            tag_name: v1.0
            files: |
              /root/file-master/file-1.0-linux-amd64